name: dlgm
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.0
  - torchvision=0.3.0
  - python=3.7.1
  - pytorch=1.1.0
  - pandas=0.24.2
  - numpy=1.16.4
  - scipy=1.2.1
  - pytz=2019.1
  - tqdm=4.32.1
